services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    environment:  
      - ENVIRONMENT=prod
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "80:8080"
    environment:  
      - ENVIRONMENT=prod