FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

RUN npm i 

RUN npm run build

FROM nginx:1.25-alpine AS production

ENV NODE_ENV production

COPY --from=builder /app/build /usr/share/nginx/react

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]